package enums;

public enum Subject {
	DATA_STRUCTURES, ALGORITHMS, DATABASES, OPERATING_SYSTEMS, SOFTWARE_TESTING, MACHINE_LEARNING, BIG_DATA_ANALYTICS,
	DATA_MINING, CYBER_SECURITY, CRYPTOGRAPHY, MARKETING_STRATEGY, CONSUMER_BEHAVIOR, DIGITAL_MARKETING,
	BRAND_MANAGEMENT, FINANCIAL_ACCOUNTING, CORPORATE_FINANCE, INVESTMENT_ANALYSIS, ECONOMETRICS, INTRO_TO_LINGUISTICS,
	SYNTAX, PHONETICS, SOCIOLINGUISTICS, NETWORK_SECURITY
}
